version: '3.8'

services:
  react-app:
    image: rina2316/my-react-app:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
